#!/data/data/com.termux/files/usr/bin/sh
echo "Installing NPM dependencies for Neiman..."
cd /data/data/com.termux/files/usr/share/neiman
npm install
echo "Installation finished. Type 'neiman' to start!"
